---
cache_dir: ~/Library/Caches/battleschool

sources:

  git:
    - name: 'osx'
      repo: 'https://github.com/ashishrv/ansible-osx.git'
      playbooks:
         - vagrant.yml
         - virtualbox.yml
         - alfred.yml
         - chrome-beta.yml
         - chrome-canary.yml
         - dropbox.yml
         - java8.yml
         - iterm2.yml
         - macvim.yml
         - adium.yml
         - slate.yml



