#!/bin/bash

curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.0.4-10.6-SnowLeopard.dmg
hdiutil attach MacPorts-2.0.4-10.6-SnowLeopard.dmg
sudo installer -verbose -pkg /Volumes/MacPorts-2.0.4/MacPorts-2.0.4.pkg -target /
sudo port -v selfupdate
# hdiutil detach -verbose /dev/disk1s2
# rm MacPorts-2.0.4-10.6-SnowLeopard.dmg




