#!/bin/bash
source ~/.bash_profile
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -n "$1" ]; then
	if [ -f "$DIR/myvirtualenv/$1" ]; then
	    echo "pip requirement file exists at $DIR/myvirtualenv/"
	    mkvirtualenv --no-site-packages $1;
	    workon $1;
	    pip install -r "$DIR/myvirtualenv/$1"
	    
	else
	    echo "env does not exists at $DIR/myvirtualenv/"
	fi
fi

