#! /bin/bash

[ -f ./ez_setup.py ] || curl -O http://peak.telecommunity.com/dist/ez_setup.py
/opt/local/bin/python ez_setup.py
/opt/local/bin/python ez_setup.py -U setuptools --prefix=~
rm ez_setup.py
[ -f /opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/easy_install ] || echo "setuptools has not been installed"
[ -f /opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/easy_install ] && echo "setuptools has been installed"
/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/easy_install pip
/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/pip install yolk
/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/pip install virtualenv
/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/pip install virtualenvwrapper










