#!/bin/bash
##
#
# Install or Update Boxen
#
##

# 
promptyn () {
    while true; do
        read -p "$1 " yn
        case $yn in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            '' ) return 1;;
            * ) echo "Defaulting to : No." return 1;;
        esac
    done
}

#
# Create package / archive directories
#

if promptyn "Do you want to start clean? Y/N"; then
    # remove home ruby directory
	rm -rf ~/.rbenv
	rm -rf ~/.rvm
	rm -rf /opt/boxen
	# Bash is the default shell
	chsh -s /bin/bash
	# Boxen setup
	sudo mkdir -p /opt/boxen
	userid=$(id -u -n)
	sudo chown ${userid}:admin /opt/boxen
	git clone https://github.com/ashishrv/macboxen.git /opt/boxen/repo
else
    echo "Skipping setup from scratch .."
fi

# Get into boxen environment
#if [ "\`type -t env_boxen\`" = 'function' ]; then
#	echo "Boxen environment available"
#else
#	echo "Could not switch to Boxen environment"
#	exit 1
#fi

#env_boxen

# Keep a clean copy of Puppetfile from github
cd /opt/boxen/repo
git checkout Puppetfile
cd $HOME/Dotfiles/installscripts

# Copy my customized specific modules 
cp $HOME/Dotfiles/installscripts/boxen/ashishrv.pp /opt/boxen/repo/modules/people/manifests/

# Update Puppetfile with source information / customizations
cat $HOME/Dotfiles/installscripts/boxen/Puppetfile_ext >> /opt/boxen/repo/Puppetfile

# Run boxen
/opt/boxen/repo/script/boxen --no-fde

# get out of boxen environment
#deactivate_boxen

echo "Boxen environment has been updated .."
echo



