#!/bin/bash

#------------------------------------------------
# BASH PROFILE - Load all profile fragments
#------------------------------------------------


#
##  Basic idea
#   custom functions starts with my-
#   File functions starts witrh f-
#   Directory functions starts with d-
#   Project functions starts with p-
#   Git function and commands starts with gi-
#   Docker functions and commands starts with do-
#   Python commands and function starts with pi-
#   Go commands and function starts with go-


source /usr/local/etc/bash_completion

test -e "${PROFILE}/util_editor" && source "${PROFILE}/util_editor"
test -e "${PROFILE}/util_brew" && source "${PROFILE}/util_brew"
test -e "${PROFILE}/util_bash" && source "${PROFILE}/util_bash"
test -e "${PROFILE}/util_terminal" && source "${PROFILE}/util_terminal"
test -e "${PROFILE}/util_java" && source "${PROFILE}/util_java"
test -e "${PROFILE}/util_python" && source "${PROFILE}/util_python"
test -e "${PROFILE}/util_docker" && source "${PROFILE}/util_docker"
test -e "${PROFILE}/util_navigation" && source "${PROFILE}/util_navigation"
test -e "${PROFILE}/util_files" && source "${PROFILE}/util_files"
test -e "${PROFILE}/util_search" && source "${PROFILE}/util_search"
test -e "${PROFILE}/util_apple" && source "${PROFILE}/util_apple"
test -e "${PROFILE}/util_process" && source "${PROFILE}/util_process"
test -e "${PROFILE}/util_others" && source "${PROFILE}/util_others"
test -e "${PROFILE}//util_latex" && source "${PROFILE}/util_latex"
test -e "${PROFILE}/util_mercurial" && source "${PROFILE}/util_mercurial"
test -e "${PROFILE}/util_git" && source "${PROFILE}/util_git"
test -e "${PROFILE}/util_go" && source "${PROFILE}/util_go"
test -e "${PROFILE}/util_docker" && source "${PROFILE}/util_docker"
test -e "${PROFILE}/util_tmux" && source "${PROFILE}/util_tmux"
test -e "${PROFILE}/util_prompt" && source "${PROFILE}/util_prompt"
test -e "${PROFILE}/util_completions" && source "${PROFILE}/util_completions"
test -e "${PROFILE}/util_project" && source "${PROFILE}/util_project"
test -e "${PROFILE}/util_personal" && source "${PROFILE}/util_personal"
test -e "${PROFILE}/util_works" && source "${PROFILE}/util_works"


alias dot-reload=". ~/.bash_profile"
