#!/bin/bash
#------------------------------------------------
# File commands
#------------------------------------------------


# Create a ZIP archive of a file or folder (zipf file|folder)
zip-unsecure () { zip -r "$1".zip "$1" ; }
zip-secure () { zip -er "$1".zip "$1" ; }

# num-files:  Count of non-hidden files in current dir
alias f-num-files='echo $(ls -1 | wc -l)'
# make-1mb:      Creates a file of 1mb size (all zeros)
alias f-make-1mb='mkfile 1m ./1MB.dat'
# make-5mb:      Creates a file of 5mb size (all zeros)
alias f-make-5mb='mkfile 5m ./5MB.dat'
# make-10mb:     Creates a file of 10mb size (all zeros)
alias f-make-10mb='mkfile 10m ./10MB.dat'

# archive shortcuts
tar-compress () { tar -zcf "$1".tar.gz "$1"; }
tar-extract () { tar xzf "$1"; }

# Extract about anything
extract ()
{
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xvjf $1        ;;
            *.tar.gz)    tar xvzf $1     ;;
            *.bz2)       bunzip2 $1       ;;
            *.rar)       unrar x $1     ;;
            *.gz)        gunzip $1     ;;
            *.tar)       tar xvf $1        ;;
            *.tbz2)      tar xvjf $1      ;;
            *.tgz)       tar xvzf $1       ;;
            *.zip)       unzip $1     ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1    ;;
            *)           echo "'$1' cannot be extracted via >extract<" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# colorized man support
man-color () {
env \
  LESS_TERMCAP_mb=$'\e'"[1;31m" \
  LESS_TERMCAP_md=$'\e'"[1;31m" \
  LESS_TERMCAP_me=$'\e'"[0m" \
  LESS_TERMCAP_se=$'\e'"[0m" \
  LESS_TERMCAP_so=$'\e'"[1;44;33m" \
  LESS_TERMCAP_ue=$'\e'"[0m" \
  LESS_TERMCAP_us=$'\e'"[1;32m" \
  command man "$@"
}

# Man pages : Required only for Mac OSX
if [ "$(uname)" == "Darwin" ]; then
   # Open a manpage in Preview, which can be saved to PDF
   man-pdf() { man -t "${1}" | open -f -a /Applications/Preview.app ; }
fi
