#!/bin/bash
#------------------------------------------------
# TMUX
#------------------------------------------------

# Activate bash completion only if using bash
if [[ "$BASH" == "/bin/bash" ]]; then
      if [ -f /usr/local/etc/bash_completion.d/tmux ]; then
      source /usr/local/etc/bash_completion.d/tmux
      fi
fi

TMUXP_BIN=/Users/ashish/.vpython/3.7.4/master/bin/tmuxp

function _my_mux(){
  local cur prev opts
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  all_arguments="--help --ls --ls-profile --start-profile --save-profile --load-all --kill-session --kill-server --attach-session"
  if [[ "$prev" == "mux" ]]; then
        COMPREPLY=($( compgen -W "${all_arguments}" -- $cur ) )
        return
  fi
  if [[ "$cur" == -* ]]; then
        COMPREPLY=($( compgen -W "${all_arguments}" -- $cur ) )
        return
  fi
  case "$prev" in
      --help )
            COMPREPLY=()
            return
            ;;
      --load-all )
            COMPREPLY=()
            return
            ;;
      --kill-server )
            COMPREPLY=()
            return
            ;;
      --ls )
            COMPREPLY=()
            return
            ;;
      --ls-profile )
            COMPREPLY=()
            return
            ;;
      --save-profile )
            COMPREPLY=()
            return
            ;;
      --attach-session )
            local tmuxlist=`tmux ls | cut -d ':' -f1`
            COMPREPLY=($( compgen -W "${tmuxlist}" -- $cur ) )
            return
            ;;
      --kill-session )
            local tmuxlist=`tmux ls | cut -d ':' -f1`
            COMPREPLY=($( compgen -W "${tmuxlist}" -- $cur ) )
            return
            ;;
      --start-profile )
            local profilelist=`ls -1 $HOME/.tmuxp/ | cut -d '.' -f1`
            COMPREPLY=($( compgen -W "${profilelist}" -- $cur ) )
            return
            ;;
      --* )
            COMPREPLY=($( compgen -W "${all_arguments}" -- $cur ) )
            return
            ;;
  esac
  if [[ "$cur" != -* ]]; then
        COMPREPLY=($( compgen -W "${all_arguments}" -- $cur ) )
        return
  fi
}


function my-mux(){
  numargs=$#
  action=
  for ((i=1 ; i <= numargs ; i++))
  do
    if [[ "x$1" == "x" ]];  then
        break
    fi
    case "$1" in
        --help)
                echo "Command line options:"
                echo "  --help            Show this help"
                echo "  --ls              Show active tmux sessions"
                echo "  --ls-profile      Show tmuxp profiles"
                echo "  --start-profile   Start tmuxp profile"
                echo "  --save-profile    Save a current session as tmuxp profile"
                echo "  --load-all         Load all tmuxp profiles"
                echo "  --kill-session    Kill a tmux session"
                echo "  --kill-server     Kill tmux server"
                echo "  --attach-session  Attach to active tmux session"
                break
                ;;
        --ls)
                tmux ls | cut -d ':' -f1
                break
                ;;
        --ls-profile)
                echo "All tmuxp profiles located @ $HOME/.tmuxp"
                ls  $HOME/.tmuxp/ | fmt -1
                break
                ;;
        --kill-server)
                echo "Killing all tmux sessions"
                tmux kill-server
                break
                ;;
        --kill-session)
                var_session=$2
                shift 2
                echo "Killing tmux session: ${var_session}"
                tmux kill-session -t ${var_session}
                break
                ;;
        --start-profile)
                var_profile=$2
                shift 2
                tmux ls | cut -d":" -f 1 | grep "${var_profile}" 2> /dev/null
                if [[ $? -eq 0 ]]; then
                    echo "Following profile has already been loaded: ${var_profile}"
                    echo ""
                else
                    echo "Starting tmux profile: ${var_profile}"
                    ${TMUXP_BIN} load ${var_profile} --yes -d
                fi
                break
                ;;
        --save-profile)
                var_profile=$2
                shift 2
                ${TMUXP_BIN} freeze ${var_profile}
                break
                ;;
        --load-all)
                echo "Loading all tmuxp profiles"
                for x in `ls -1 $HOME/.tmuxp/`;
                do
                  profile="${x%.*}"
                  fact=`tmux list-sessions | grep ${profile}`
                  if [[ "x${fact}" == "x" ]]; then
                      echo "Loading profile: $profile"
                      ${TMUXP_BIN} load ${profile} --yes -d
                  fi
                done
                break
                ;;
          --attach-session)
                var_session=$2
                shift 2
                tmux ls | grep ${var_session} | grep attached
                if [[ $? -eq 0 ]]; then
                    echo "Following profile has already been attached to: ${var_session}"
                    echo ""
                else
                    tmux attach-session -t ${var_session}
                fi
                break
                ;;
    esac
  done
}

complete -F _my_mux my-mux
